services:
  - type: web
    name: lexdiary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lexdiary.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lexdiary.settings
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: ioinhcvri9sy(18(s!rcvxw8^72fwcm5fmgi(jp_bt5rbq)k-u
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
