# Generated by Django 5.2.1 on 2025-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
